### ISSUE TITLE
undefined method `get_database_list' for <InfluxDB::Client:0xXXX>

### ISSUE THREAD

**Issue by jperville** [bdangit/chef-influxdb#69]
Hello there,

I found out this morning that the latest versions of the influxdb [gem](https://github.com/influxdb/influxdb-ruby) do not support influxdb 0.8 anymore. Current version is 0.2.2 which only supports influxdb 0.9. Version 0.1.9 is the last version of the gem to support influxdb 0.8.x.

If installing influxdb 0.8 with this cookbook without specifying the version of influxdb gem to use then chef will fail with the following message:

```sh
NoMethodError: undefined method `get_database_list' for #<InfluxDB::Client:0x00000002085780>
```

My workaround is to use the attribute to specify the gem version: `node.override['influxdb']['gem']['version'] = 0.1.9` introduced in #62.

**Comment by jperville** [comment]
After playing with #66 (which adds support for influxdb gem 0.2.x, needed for influxdb 0.9), I think that this cookbook cannot support both versions 0.8 and version 0.9 of influxdb without ugly hacks in the code. Maybe add a major release from which only version 0.9 will be supported (especially now that version 0.8 of influxdb is not supported anymore).

**Comment by jakedavis** [comment]
Hey @jperville. So I merged #66 and bumped the cookbook to 3.0.0. I think that will satisfy this issue?

**Comment by jperville** [comment]
Thank you @jakedavis . I need to port my cookbooks to influxdb 0.9 now :-)
Will let you know of my success then you can push a new release to the supermarket.

**Comment by jperville** [comment]
I played a bit with the new cookbook version but still need a lot of work for me to switch yet. In particular, I struggle with the init file (from the influxdb tarball?) which hardcodes the path of the configuration file to `/etc/opt/influxdb/influxdb.conf`, a path which I'd rather customize (and which is forced with node.set to `"#{node[:influxdb][:install_root_dir]}/shared/config.toml"` later in the recipe, thus breaking the init file).

Need to have a closer look at these (and maybe search for solutions in the existing PRs) during the week-end. Thanks for the work @jakedavis

**Comment by kemra102** [comment]
Even in 3.0.0 I'm still seeing this error:

```
ERROR: influxdb_database[grafana] (graphing::default line 17) had an error: NoMethodError: undefined method `get_database_list' for #<InfluxDB::Client:0x00000007348800>
```

**Comment by jperville** [comment]
I managed today to make everything work using the current master version (and after fixing #72).

**Comment by bdangit** [comment]
Looks like we are good to close here.  Reopen if issues appear on the master.
